version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "1337:80"
    volumes:
      - ./src:/var/www/html