apiVersion: v1
kind: Service
metadata:
  name: tellulf-service
spec:
  type: NodePort
  selector:
    app: tellulf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30001