apiVersion: v1
kind: Service
metadata:
  name: tellulf-service
  namespace: tellulf
spec:
  type: NodePort
  selector:
    app: tellulf
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000