apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kvasbo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tellulf-service
            port:
              number: 80
      - pathType: Prefix
        path: /tellulf
        backend:
          service:
            name: tellulf-service
            port:
              number: 80