name: Build and push to Github Container Registry

on:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-tellulf:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.3
            - name: Install dependencies
              run: yarn install
            - name: Lint with ESLint
              run: yarn run lint
            - name: Build sass
              run: npx sass sass:assets/css
            - name: Build typescript server
              run: npx tsc --p tsconfig.server.json
            - name: Build typescript client
              run: npx tsc --p tsconfig.client.json
            - name: Archive built files
              uses: actions/upload-artifact@v3
              with:
                  name: built-tellulf
                  path: |
                      build
                      assets/js
                      assets/css
    upload-image:
        needs: build-tellulf
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.3
            - name: Install dependencies
              run: yarn install --production
            - name: Download artifact
              uses: actions/download-artifact@v3
              with:
                  name: built-tellulf
            - name: Copy built stuff into clean directories
              run: |
                  rm -rf build
                  rm -rf assets/js
                  rm -rf assets/css
                  mkdir build
                  mkdir assets/js
                  mkdir assets/css
                  cp -r built-tellulf/build/* build
                  cp -r built-tellulf/assets/js/* assets/js
                  cp -r built-tellulf/assets/css/* assets/css
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20.3
            - name: Install dependencies
              run: yarn install
            - name: Lint with ESLint
              run: yarn run lint
            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Build and push Docker image
              uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
