name: Build and push to Dockerhub

on:
    push:
        branches:
            - main

jobs:
    build-container:
        name: Build and push to Dockerhub
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      kvasbo/tellulf
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                      type=ref,event=branch
                      type=sha
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_ACCESS_KEY }}
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push
              id: docker_build
              uses: docker/build-push-action@v3
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  builder: ${{ steps.buildx.outputs.name }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
            - name: Webhook
              uses: joelwmale/webhook-action@448a17bf857ead98546cfbdbe3b9d4cf979dda95
              with:
                  url: ${{ secrets.PORTAINER_WEBHOOK }}
                  body: '{"message": "New image pushed to Dockerhub"}'
