name: Build, push to Dockerhub and deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-container:
    name: Build and push to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_KEY }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./Dockerfile
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tellulf:latest
      - name: 'Upload application config'
        uses: actions/upload-artifact@v3
        with:
          name: k8n-config
          path: application.yml
  do-apps:
    name: Deploy to DigitalOcean apps
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Deploy to DigitalOcean
        run: doctl apps create-deployment ${{ secrets.DIGITALOCEAN_APP_ID }}
  do-k8n:
    name: Deploy to DigitalOcean k8n
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Install Digitalocean Kubernetes
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: kvasbo-clusterfuck
      # - name: Checkout the repo (to get applicaton.yml)
      #   uses: actions/checkout@v2
      - name: Download config
        uses: actions/download-artifact@v3
        with:
          name: k8n-config
      - name: Deploy to Kubernetes
        run: kubectl apply -f application.yml