name: Build and push to Dockerhub

on:
    push:
        branches:
            - main

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-container:
        name: Build and push to Dockerhub
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v3
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: |
                      kvasbo/tellulf
                  tags: |
                      type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
                      type=ref,event=branch
                      type=sha
            - name: Login to Github Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2
            - name: Build and push to Github
              id: docker_build_github
              uses: docker/build-push-action@v3
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  builder: ${{ steps.buildx.outputs.name }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
