name: Build and push to Github Container Registry

on:
    push:
        branches:
            - '*' # Pushes to any branch

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    NODE_VERSION: 20

jobs:
    build:
        runs-on: self-hosted
        name: Lint, build and push
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Tailscale
              uses: tailscale/github-action@v2
              with:
                oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
                oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
                tags: tag:ci
                version: 1.58.2
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: yarn
            - name: Extract metadata (tags, labels)
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                    type=ref, event=branch
                    type=sha
            - name: Install dependencies
              run: yarn install
            - name: Lint
              run: yarn run lint
            - name: Build
              run: yarn run build
            - name: Test
              run: yarn run test
            - name: Log in to the registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  platforms: linux/amd64
