name: Build and push to Github Container Registry

on:
    push:
        branches:
            - '*' # Pushes to any branch

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}
    NODE_VERSION: 20

jobs:
    build:
        runs-on: ubuntu-latest
        name: Lint and Build
        permissions:
            contents: read
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
              with: # Set up multiarch build
                  platforms: linux/amd64,linux/arm64
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: yarn
            - name: Extract metadata (tags, labels)
              id: meta
              uses: docker/metadata-action@v4
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Install dependencies
              run: yarn install
            - name: Lint
              run: yarn run lint
            - name: Build
              run: yarn run build
            - name: Log in to the registry
              uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: false
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
