name: Define Kubernetes services

on: workflow_dispatch

do-k8n:
    name: Deploy to DigitalOcean k8s
    needs: build-container
    runs-on: ubuntu-latest
    steps:
      - name: Install Digitalocean Kubernetes
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: ${{ secrets.K8S_CLUSTER }}
      - name: Delete old secrets
        run: kubectl delete secret tellulf-secrets --ignore-not-found
      - name: Setup secrets # Should run before any applications are deployed on on k8s
        run: |
          kubectl create secret generic tellulf-secrets \
            --from-literal=YR_URL_FORECAST='${{ secrets.YR_URL_FORECAST }}' \
            --from-literal=YR_URL_NOWCAST='${{ secrets.YR_URL_NOWCAST }}' \
            --from-literal=CAL_FELLES='${{ secrets.CAL_FELLES }}' \
            --from-literal=CAL_BIRTHDAYS='${{ secrets.CAL_BIRTHDAYS }}' \
      - name: Checkout the repo (to get applicaton.yml)
        uses: actions/checkout@v3
      - name: Deploy application to Kubernetes
        run: kubectl apply -f ./k8s/application.yml
      - name: Deploy load balancer to Kubernetes
        run: kubectl apply -f ./k8s/loadbalancer.yml
      - name: Setup ingress
        run: kubectl apply -f ./k8s/ingress.yml
      - name: Setup service
        run: kubectl apply -f ./k8s/service.yml